{% set name = "stata_kernel" %}
{% set version = "1.14.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stata_kernel-{{ version }}.tar.gz
  sha256: 3f08af8bd12c7b320a36c0ddeba1587b71a8ad2545dbe739c8a12fb694c40ece

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
requirements:
  host:
    - python
    - pip
    - poetry-core >=1.8.1
  run:
    - beautifulsoup4 >=4.6.3
    - pandas >=1.0.0
    - numpy >= 1.22.0
    - pygments >=2.2,<3.0
    - pexpect >=4.6.0
    - packaging >=17.1
    - pillow >=5.2.0
    - pywin32 >=223  # [win]
    - fake-useragent >=2.0.0,<3.0.0
    - ipython >=7.34,<8.0
    - ipykernel >=4.8.2,<5.0
    - jupyter-client >=6.1.12,<7.0
    - jupyter-core >=5.8.1,<6.0
    - notebook >=6.5.7,<7.0
    - nbclient >=0.8,<1.0

test:
  requires:
    - pip
  commands:
    - pip check
    - export CONTINUOUS_INTEGRATION=1  # [unix]
    - set CONTINUOUS_INTEGRATION=1  # [win]
    - python -c "import stata_kernel"

about:
  home: https://github.com/kylebarron/stata_kernel
  summary: A Jupyter kernel for Stata. Works with Windows, macOS, and Linux. Preserves program state.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stanmart
