{% set name = "stata_kernel" %}
{% set version = "1.14.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stata_kernel-{{ version }}.tar.gz
  sha256: 3f08af8bd12c7b320a36c0ddeba1587b71a8ad2545dbe739c8a12fb694c40ece

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pip                                    # [build_platform != target_platform]
    - setuptools >=38.6.0                    # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools >=38.6.0
  run:
    - beautifulsoup4 >=4.6.3
    - ipykernel >=4.8.2
    - ipython >=6.5.0
    - jupyter_client >=5.2.3
    - packaging >=17.1
    - pandas >=1.0.0
    - pexpect >=4.6.0
    - pillow >=5.2.0
    - pygments >=2.2.0
    - python
    - pywin32 >=223  # [win]
    - requests >=2.19.1

test:
  requires:
    - pip
  commands:
    - pip check
    - export CONTINUOUS_INTEGRATION=1  # [unix]
    - set CONTINUOUS_INTEGRATION=1  # [win]
    - python -c "import stata_kernel"

about:
  home: https://github.com/kylebarron/stata_kernel
  summary: A Jupyter kernel for Stata. Works with Windows, macOS, and Linux. Preserves program state.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stanmart
